[package]
name = "cmdrec"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "^3.2", features = ["derive"] }
rand = "^0.8"
standard_paths = "^1.0"

[dev-dependencies]
tempfile = "^3.3"
